### ISSUE TITLE
Get depth matrix

### ISSUE THREAD

**Issue by SashaMalysheva** [SashaMalysheva/SPb-AU-LeapMotion#3]

**Comment by avgaydashenko** [comment]
Rebryk's code: http://pastebin.com/XSmg7DZK
Main page of source: opencv.org

Pages with some algorithms: 
https://en.wikipedia.org/wiki/Feature_detection_%28computer_vision%29#Feature_detectors
http://stackoverflow.com/questions/19540138/which-feature-detector-algorithm-is-simplest-for-learning

**Comment by SashaMalysheva** [comment]
by dedicated point find its distance: https://community.leapmotion.com/t/sdk-2-1-raw-data-get-pixel-position-xyz/1604/12

Object search: http://www.mathworks.com/help/vision/ref/matchfeatures.html

**Comment by avgaydashenko** [comment]
Matlab in java:
https://code.google.com/archive/p/matlabcontrol/
https://code.google.com/archive/p/matlabcontrol/wikis/Walkthrough.wiki

**Comment by SashaMalysheva** [comment]
OpenCV
Feature Detection -http://docs.opencv.org/2.4/doc/tutorials/features2d/feature_detection/feature_detection.html
